---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydp
  namespace: argocd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/cycle
          ports:
            - containerPort: 80

---           
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 80
